src/Entity/task.php
<?php

namespace DocRep;

use Doctrine\ORM\Mapping as ORM;

/**
 * Class task
 * @package App/Entity
 * @ORM\Table(name="task")
 * @ORM\Entity
 */

class task
{
    /**
     * @var int
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\Column(type="string")
     */
    private $name;
    /**
     * @var string
     * @ORM\Column(type="string")
     */
    public $params;
    /** @ORM\Column(type="string", columnDefinition="ENUM('WAIT', 'ACCEPTED', 'DONE', 'REJECTED', 'BROKEN')") */
    private $state;
    /** @ORM\Column(type="datetime") */
    private $date_create;
    /** @ORM\Column(type="datetime") */
    private $date_done;


    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getDateCreate()
    {
        return $this->date_create;
    }

    /**
     * @return mixed
     */
    public function getDateDone()
    {
        return $this->date_done;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @return mixed
     */
    public function getParams()
    {
        return $this->params;
    }

    /**
     * @return mixed
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * @param mixed $date_create
     */
    public function setDateCreate()
    {
        $this->date_create = new \DateTime("now");
    }

    /**
     * @param mixed $date_done
     */
    public function setDateDone()
    {
        $this->date_done = new \DateTime("now");
    }

    /**
     * @param mixed $name
     */
    public function setName($name): void
    {
        $this->name = $name;
    }

    /**
     * @param mixed $params
     */
    public function setParams($params): void
    {
        $this->params = $params;
    }

    /**
     * @param mixed $state
     */
    public function setState($state): void
    {
        $this->state = $state;
    }

}

src/Controller/TaskmngrController.php
<?php

namespace App\Controller;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use http\Client\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use DocRep;
use App\Services\csv;
use App\Services\products;
use App\Services\tasks\SetState;
use App\Commands\Console;


class TaskmngrController extends AbstractController
{

    private $path;

    /**
     * @return mixed
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * @Route("/taskmngr", name="taskmngr")
     */
    public function index(csv $csv, Console $console)
    {
        $state = new SetState();
        $task = new DocRep\task();
        $em = $this->getDoctrine()->getManager()->getRepository('App:task');
        $obj = $em->findAll();

        if (!$obj) {
            throw $this->createNotFoundException(
                'No tasks found'
            );
        }else{
            return $this->render('taskmngr/index.html.twig', [
                'controller_name' => 'TaskmngrController',
                'obj' => $obj
            ]);
        }
    }



    /**
     * @Route("/taskmngr/{id}/{status}", )
     */
    public function change(int $id, string $status)
    {
        $em = $this->getDoctrine()->getManager()->getRepository('App:task');
        $post = $em->find($id);


        if ($status == 'run'){
            $post->setState('ACCEPTED');
            $this->getDoctrine()->getManager()->flush();

        }
        else {
            $this->getDoctrine()->getManager()->remove($post);
            $this->getDoctrine()->getManager()->flush();
        }

        products::reload('taskmngr');
    }

    /**
     * @Route("/taskmngr/{status}", )
     */
    public function StartTasks(string $status)
    {
        $em = $this->getDoctrine()->getManager()->getRepository('App:task');
        $path = $em->findOneBy(['state'=>'ACCEPTED']);

        if ($status == 'start' && isset($path))
        {
            $this->path = (get_object_vars($path))['params'];
            $TaskSerialize = serialize($this->path);
            file_put_contents('CsvPath', $TaskSerialize);

            try{
                $cmd = new Console();

                $cmd_csv = $cmd->execute(['systemctl', 'start', 'symcsv.service']);
                products::reload('main');
                return xdebug_var_dump($cmd_csv);
            }catch (Exception $e){
                xdebug_var_dump($e);
            }
        }
    }
}

templates/taskmngr/index.html.twig
{% include 'main/header.twig' %}
<div class="wrap">
    <div class="example-wrapper">

        <div class="content">
            <h1>Hello {{ controller_name }}!</h1>
            This friendly message is coming from:
            <ul>
                <li>Your controller at <code><a href="{{ '/home/imag2/src/Controller/AddProductController.php'|file_link(0) }}">src/Controller/AddProductController.php</a></code></li>
                <li>Your template at <code><a href="{{ '/home/imag2/templates/add_product/index.html.twig'|file_link(0) }}">templates/add_product/index.html.twig</a></code></li>
            </ul>
        </div>
    </div>
    <div class="content">

        <form class="table _task" method="get" action="/main">

                {% for task in obj %}
                <ul>
                    <li>{{ task.id }}</li>
                    <li>{{ task.name }}</li>
                    <li>{{ task.params }}</li>
                    <li>{{ task.state }}</li>
                    <li>{{ task.dateCreate|date('Y-m-d H:i:s') }}</li>
                    <li>{{ task.dateDone|date('Y-m-d H:i:s') }}</li>
                    <li><a class="ico" href="{{ app.request.uri }}/{{ task.id }}/run"><i class="fas fa-play"></i></a></li>
                    <li><a class="ico" href="{{ app.request.uri }}/{{ task.id }}/delete"><i class="fas fa-trash-alt"></i></a></li>
                </ul>
                {% endfor %}

        </form>



    </div>
    <div class="content">
        <div class="links">
            <a href="/main">BACK TO MAIN</a>
        </div>
    </div>
</div>
{% include 'main/bottom.twig' %}